### ISSUE TITLE
more training data required ,pls

### ISSUE THREAD

**Issue by gjpicker** [benliaowc/anime_face_conditional-GAN#1]
Hi  benliaowc 
   could you pls share more train face_anime data ? some storage like google_cloud  or baidu_cloud will help us .  size: 256*256  optional 
^^^^^^^^   您能否提供更多训练数据，比如存放在google云 or baidu云？

**Comment by wchliao** [comment]
Hi.
I have updated the training data link in Training Data section.
Let me know if you have further issues.
